# Introdução ao TensorFlow

# 1. Introdução

O __TensorFlow__ é uma biblioteca de software de código aberto. O TensorFlow foi originalmente desenvolvido por pesquisadores e engenheiros que trabalham na `Google Brain Team` da organização de pesquisa Machine Intelligence do Google para fins de Machine Learning e pesquisa de Deep Learning, mas o sistema é geral o suficiente para ser aplicado em uma ampla variedade de outros domínios.  
  
Vamos primeiro tentar entender o que a palavra TensorFlow realmente significa!  
  
TensorFlow é basicamente uma biblioteca de software para computação numérica usando __Grafos de Fluxo de Dados__ onde:  
  
 - __nodes (nós)__ - No gráfico representam operações matemáticas;  
 - __edges (arestas)__ - Arestas no gráfico representam as matrizes de dados multidimensionais `(denominadas tensores)` comunicadas entre elas. `(Por favor, note que o tensor é a unidade central de dados no TensorFlow)`.
 
__NOTE:__  
  
 - __Tensor__ = Objeto matemático
 - __Flow__ = Fluxo  
 - __TensorFlow__ = Fluxo de um objeto matemático  
  
Considere o diagrama abaixo:  
  
![title](images/graph1-geeks.png)  
  
 - Aqui, __add é um node(nó)__ que representa a operação de adição;  
 - __a__ e __b__ são tensores de entrada;  
 - E __c__ é o tensor resultante.  
  
> Essa arquitetura flexível permite que você implante computação em uma ou mais CPUs ou GPUs em um desktop, servidor ou dispositivo móvel com uma única API.

### 1.1. API do TensorFlow

O __TensorFlow__ fornece várias APIs. Estas podem ser classificados em 2 categorias principais:  
  
 - __Low level API:__  
   - Controle completo de programação;  
   - Recomendado para pesquisadores de Machine Learning;  
   - Fornece ótimos níveis de controle sobre os modelos;  
   - O __TensorFlow Core__ é a API de baixo nível do TensorFlow.  
 - __High level API:__  
   - Construído em cima do __TensorFlow Core__;  
   - Mais fácil de aprender e usar do que o __TensorFlow Core__;  
   - Tornar tarefas repetitivas mais fáceis e mais consistentes entre diferentes usuários;  
   - __tf.contrib.learn__ é um exemplo de uma API de alto nível.

# 2. Grafo Computacional

Qualquer programa do __TensorFlow Core__ pode ser dividido em duas seções distintas:  
  
 - Construindo o __grafo computacional__. Um __grafo computacional__ nada mais é do que uma série de operações do TensorFlow organizadas em um grafo de nodes (nós).  
 - Executando o grafo computacional. Para realmente avaliar os nós, devemos executar o grafo computacional dentro de uma __sessão (Session)__. Uma sessão encapsula o controle e o estado do tempo de execução do TensorFlow.  
  
Agora, vamos escrever nosso primeiro programa TensorFlow para entender o conceito acima:

In [2]:
# Importa a biblioteca TensorFlow. 
import tensorflow as tf 

# Criando nodes(nós) em um Grafo Computacional.
node1 = tf.constant(3, dtype=tf.int32) 
node2 = tf.constant(5, dtype=tf.int32) 
node3 = tf.add(node1, node2) 

# Cria uma instância do objeto Session(), ou seja, uma sessão.
sess = tf.Session() 

# Imprime o resultado da operação de adição no Grafo Computacional.
print("A soma dos node1 e node2 é:",sess.run(node3)) 

# Fecha a sessão.
sess.close()

A soma dos node1 e node2 é: 8


Vamos tentar entender o código acima:  
  
__Step 1: Criar um Grafo Computacional:__  
Ao criar um grafo computacional, queremos dizer definir os nodes(nós). O Tensorflow fornece diferentes tipos de nodes(nós) para uma variedade de tarefas. `Cada node (nó) usa zero ou mais tensores como entradas e produz um tensor como saída`.
 - No programa acima, os nós __node1__ e __node2__ são do tipo __tf.constant__. Um node(nó) constante não recebe entradas e gera um valor que armazena internamente. Note que também podemos especificar o tipo de dados do tensor de saída usando o argumento __dtype__:  
   - __node1 = tf.constant(3, dtype=tf.int32)__  
   - __node2 = tf.constant(5, dtype=tf.int32)__  
 - __node3__ é do tipo __tf.add__. Leva dois tensores como entrada e retorna sua soma como tensor de saída:  
   - __node3 = tf.add(node1, node2)__  
  
__Step 2: Executa o Grafo Computacional:__  
Para executar o Grafo Computacional, precisamos criar uma __sessão (Session)__. Para criar uma sessão, simplesmente fazemos:  
  
> __sess = tf.Session()__  
  
Agora, podemos invocar o método __run()__ do objeto __Session()__ para realizar cálculos em qualquer nó:  
  
> __print("A soma dos node1 e node2 é:",sess.run(node3))__  
  
Finalmente, fechamos a sessão usando:  
  
> __sess.close()__  

### 2.1. Trabalhando com Sessões TensorFlow  
Outro (e melhor) método de trabalhar com sessões é usar um bloco como este:

In [3]:
with tf.Session() as sess:
  print("A soma dos node1 e node2 é:",sess.run(node3)) 

A soma dos node1 e node2 é: 8


A vantagem dessa abordagem é que você __não precisa para fechar a sessão explicitamente__ porque ela fica automaticamente fechada uma vez que o controle sai do âmbito do bloco __with__.

# 3. Começando com TensorFlow

### 3.1. Hello World com TensorFlow

In [4]:
# Importa a biblioteca TensorFlow.
import tensorflow as tf

In [5]:
# Verifica a versão atual do T
tf.__version__

'1.9.0'

In [6]:
# Cria um tensor, esse tensor é adicionado como um node(nó) no grafo.
hello = tf.constant('Hello, TensorFlow!')

In [7]:
# Exibe o tensor criado.
print(hello)

Tensor("Const_4:0", shape=(), dtype=string)


In [8]:
# Inicia a sessão TensorFlow - Cria uma instância do objeto Session e salva na variável "sess".
sess = tf.Session()

In [9]:
# Exibe a sessão criada.
print(sess)

In [10]:
# Executa o Grafo Computacional
print(sess.run(hello))

b'Hello, TensorFlow!'


# 4. Variáveis

O __TensorFlow__ também possui nodes(nós) variáveis que podem conter dados variáveis. Eles são usados principalmente para manter e atualizar parâmetros de um modelo de treinamento.  
  
> Variáveis são __buffers na memória contendo tensores__. Eles devem ser explicitamente inicializados e podem ser salvos no disco durante e após o treinamento. Você pode restaurar os valores salvos posteriormente para exercitar ou analisar o modelo.  
  
Uma diferença importante a notar entre uma __constante__ e uma __variável__ é:  
  
 - O valor de uma __constante__ é armazenado no grafo e seu valor é replicado sempre que o grafo é carregado.  
 - Uma __variável__ é armazenada separadamente e pode estar em um servidor de parâmetros.  
  
Veja o exemplo abaixo usando variáveis:

In [11]:
# Importa a biblioteca TensorFlow
import tensorflow as tf 

# Cria um node(nó) no Grafo Computacional.
node = tf.Variable(tf.zeros([2,2])) 

# Executa o Grafo Computacional.
with tf.Session() as sess: 
  sess.run(tf.global_variables_initializer()) # Inicia todas as variáveis.
  print("Valores do Tensor antes da adição:\n",sess.run(node)) # # Imprime o node.
  node = node.assign(node + tf.ones([2,2])) # Faz uma adição no node(nó) - elementwise.
  print("Valores do Tensor depois da adição:\n", sess.run(node)) # Imprime novamente o node.

Valores do Tensor antes da adição:
 [[0. 0.]
 [0. 0.]]
Valores do Tensor depois da adição:
 [[1. 1.]
 [1. 1.]]


# 5. Placeholders (Espaços Reservados)

Um __Placeholder (espaço reservado)__ é uma promessa para fornecer um valor mais tarde.  
  
Ao avaliar o grafo envolvendo nodes(nós) de Placeholder (espaço reservado), um parâmetro __feed_dict__ é passado para o método de __run()__ da sessão para especificar Tensores que fornecem valores concretos para esses Placeholders (espaço reservado).  
  
Considere o exemplo abaixo:

In [12]:
# Importa a biblioteca TensorFlow.
import tensorflow as tf 

# Cria nodes para o Grafo Computacional.
a = tf.placeholder(tf.int32, shape=(3,1)) # Reserva espaço para uma matriz inteira(int) - 3x1
b = tf.placeholder(tf.int32, shape=(1,3)) # Reserva espaço para uma matriz inteira(int) - 1x3
c = tf.matmul(a,b) 

# Executa o Grafo Computacional.
with tf.Session() as sess:
  print(sess.run(c, feed_dict={a:[[3],[2],[1]], b:[[1,2,3]]})) 

[[3 6 9]
 [2 4 6]
 [1 2 3]]


__NOTE:__  
Veja que nós passamos os valores para os __Placeholder (espaço reservado)__ nodes(nós) __a__ e __b__ dentro da função __run()__ com o atributo __feed_dict__:  
  
> __sess.run(c, feed_dict={a:[[3],[2],[1]], b:[[1,2,3]]})__  
  
Considere os diagramas mostrados abaixo para limpar o conceito:  
  
Inicialmente:  
  
![title](images/graph2-geeks.png)  
  
Após sessão __run()__:  

![title](images/graphgeeksstep01.png)  
  
![title](images/graphgeeksstep02.png)  
  
![title](images/graphgeeksstep03.png)

# 6. Operações Matemáticas com Tensores

### 6.1. Adição

In [13]:
# Constantes
# Cria dois "tensores" com o método "constant" do TensorFloe e passa como argumento os valores
# dos tensores, ou seja, 5 e 9.
const_a = tf.constant(5) # Tensor rank 0 ou escalar - [].
const_b = tf.constant(9) # Tensor rank 0 ou escalar - [].

In [14]:
# Exibe o Tensor "const_a".
print(const_a)

Tensor("Const_5:0", shape=(), dtype=int32)


In [15]:
# Soma os 2 tensores e salva na variável "total".
total = const_a + const_b

In [16]:
# Exibe a soma dos tensores.
print(total)

Tensor("add_3:0", shape=(), dtype=int32)


__NOTE:__  
Isso que nós fizemos até agora __não foi a soma dos tensores__. Lembram que nós trabalhamos com esses tensores como Grafos? Então, o que foi feito até agora foi:

 - __Definir os vertices(V) - Nodes__
 - __Definir às arestas(E)__

Agora o que precisamos é abrir uma Sessão TensorFlow para fazer a soma.

In [17]:
# Cria uma sessão TensorFlow, porém, agora essa sessão vai permanecer aberta.
# Depois printa a "sess.run(total)", ou seja, exibe o total(soma dos nodes).
with tf.Session() as sess:
    print('\nA soma do node1 com o node2 é: %f' % sess.run(total))


A soma do node1 com o node2 é: 14.000000


__NOTE:__  
Uma maneira bem mais simples de fazer essa operação é utilizando o método add() do TensorFlow. Veja abaixo:

In [18]:
# Cria dois tensores com os valores 5 e 9
node1 = tf.constant(5, dtype=tf.int32)
node2 = tf.constant(9, dtype=tf.int32)

# Cria um terceiro tensor "node3", porém, esse tensor vai receber a adição(add()) dos dois tensores.
node3 = tf.add(node1, node2)

# Cria a sessão TF
sess = tf.Session()
 
# Executa o grafo com o método run() da sessão, ou seja, abre a sessão.
print("\nA soma do node1 com o node2 é:", sess.run(node3))
 
# Fecha a sessão.
sess.close()


A soma do node1 com o node2 é: 14


### 6.2. Subtração

Veja abaixo que é possível criar "tensores" com valores randômicos, esses valores randômicos porem ser:

 - Normal
 - Uniforme

In [19]:
# Tensores randômicos
rand_a = tf.random_normal([3], 2.0) # Tensor randômico normal.
rand_b = tf.random_uniform([3], 1.0, 4.0) # Tensor randômico uniforme.

In [20]:
# Exibe o tensor "rand_a".
print(rand_a)

Tensor("random_normal:0", shape=(3,), dtype=float32)


In [21]:
# Exibe o tensor "rand_b".
print(rand_b)

Tensor("random_uniform:0", shape=(3,), dtype=float32)


In [22]:
# Utiliza o método subtract() do TensorFlow e passa como argumento os tensores "rand_a" e "rand_b".
# O retorno do método fica no objeto "diff".
diff = tf.subtract(rand_a, rand_b)

In [23]:
# Agora vamos abrir a sessão e exibir:
# - O valor do tensor "rand_a"
# - O valor do tensor "rand_b"
# - Executa o grafo com o métood run() do objeto Session.
with tf.Session() as sess:
    print('\nTensor rand_a: ', sess.run(rand_a))
    print('\nTensor rand_b: ', sess.run(rand_b))
    print('\nSubtração entre os 2 tensores é: ', sess.run(diff))


Tensor rand_a:  [2.929134  4.2329035 2.5424395]

Tensor rand_b:  [1.9548839 1.8865126 1.9626849]

Subtração entre os 2 tensores é:  [-0.9811697 -0.8143492  2.7723374]


### 6.3. Divisão

In [24]:
# Cria dois tensores e passa como argumento os valores 21 e 7.
node1 = tf.constant(21, dtype=tf.int32)
node2 = tf.constant(7, dtype=tf.int32)

In [25]:
# Utiliza o método div() do TensorFlow para fazer a divisão entre Tensores.
div = tf.div(node1, node2)

In [26]:
# Cria uma Sessão(Session) e executa o grafo computaiconal.
with tf.Session() as sess:
    print('\nDivisão entre os 2 tensores é: ', sess.run(div)) # Utiliza o método run() do objeto Session.


Divisão entre os 2 tensores é:  3


### 6.4. Multiplicação

#### NOTE:  
Para calcular __"A"__ vezes __"B"__, __A.B__, o número de colunas de __"A"__ tem que ser igual ao número de linhas __"B"__. Então, podemos calcular __A.B__ se:

 - __"A"__ é uma matriz - __n x m__
 - E __"B"__ é uma matriz - __m x p__ 


Uma multiplicação de matriz é a multiplicação de uma linha com os elementos de uma coluna, veja o exemplo abaixo:

![title](images/mult02.png)

In [27]:
# Criando tensores "tensor_a" e "tensor_b".
tensor_a = tf.constant([[4., 2.]])
tensor_b = tf.constant([[3.],[7.]])

In [28]:
# Exibe o tensor "tensor_a".
print(tensor_a)

Tensor("Const_11:0", shape=(1, 2), dtype=float32)


In [29]:
# Exibe o tensor "tensor_b".
print(tensor_b)

Tensor("Const_12:0", shape=(2, 1), dtype=float32)


In [30]:
# Multiplicação
# tf.multiply(X, Y) executa multiplicação element-wise 
# https://www.tensorflow.org/api_docs/python/tf/multiply
prod = tf.multiply(tensor_a, tensor_b)

In [31]:
# Executa a sessão
with tf.Session() as sess:
    print('\ntensor_a: \n', sess.run(tensor_a))
    print('\ntensor_b: \n', sess.run(tensor_b))
    print('\nProduto Element-wise Entre os Tensores: \n', sess.run(prod))


tensor_a: 
 [[4. 2.]]

tensor_b: 
 [[3.]
 [7.]]

Produto Element-wise Entre os Tensores: 
 [[12.  6.]
 [28. 14.]]


__NOTE:__  
Lembre que operações com matrizes é sempre __LINHA POR COLUNA__:  

```  
[4 , 2] x [3]  = [12 , 12]  
          [7]    [28 , 14]  
```

![title](images/mult01.png)

In [32]:
# Outro exemplo de Multiplicação de Matrizes
mat_a = tf.constant([[2, 3], [9, 2], [4, 5]])
mat_b = tf.constant([[6, 4, 5], [3, 7, 2]])

In [33]:
print(mat_a)

Tensor("Const_13:0", shape=(3, 2), dtype=int32)


In [34]:
print(mat_b)

Tensor("Const_14:0", shape=(2, 3), dtype=int32)


In [35]:
# Multiplicação
# tf.matmul(X, Y) executa multiplicação entre matrizes.
mat_prod = tf.matmul(mat_a, mat_b)

In [36]:
# Executa a sessão
with tf.Session() as sess:
    print('\nTensor mat_a: \n', sess.run(mat_a))
    print('\nTensor mat_b: \n', sess.run(mat_b))
    print('\nProduto Element-wise Entre os Tensores (Matrizes): \n', sess.run(mat_prod))


Tensor mat_a: 
 [[2 3]
 [9 2]
 [4 5]]

Tensor mat_b: 
 [[6 4 5]
 [3 7 2]]

Produto Element-wise Entre os Tensores (Matrizes): 
 [[21 29 16]
 [60 50 49]
 [39 51 30]]
