# Matrizes
Em termos gerais, uma matriz é uma array de números organizados em __linhas__ e __colunas__.

# 1. Matrizes e notação de matriz
Uma matriz organiza números em __linhas__ e __colunas__, assim:  
  
\begin{equation}A = \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6
 \end{bmatrix}
\end{equation}
  
Observe que as matrizes geralmente são nomeadas como uma letra maiúscula. Referimo-nos aos `elementos` da matriz usando o equivalente em minúscula com um indicador de linha e coluna subscrito, assim:  
  
\begin{equation}A = \begin{bmatrix}
  a_{1,1} & a_{1,2} & a_{1,3} \\
  a_{2,1} & a_{2,2} & a_{2,3}
 \end{bmatrix}
\end{equation}
  
Em Python, você pode definir uma Matriz 2-dimensional com a função __np.array()__ do NumPy:

In [1]:
# Importa a biblioteca NumPy.
import numpy as np

# Cria nossa Matriz com o método array() do NumPy.
A = np.array([[1,2,3],
              [4,5,6]])

print(A) # Imprime a Matriz.

[[1 2 3]
 [4 5 6]]


Você também pode usar o __np.matrix()__ que é uma subclasse especializada de matrizes(arrays):

In [2]:
import numpy as np

# cria uma Matriz, porém de forma especializada.
M = np.matrix([[1,2,3],
               [4,5,6]])

print(M) # Imprime a Matriz.

[[1 2 3]
 [4 5 6]]


Existem algumas diferenças de comportamento entre __array()__ e __matrix()__ - Especialmente com relação à multiplicação (que vamos explorar mais tarde). Você pode usar qualquer um, mas os programadores Python mais experientes que precisam trabalhar com vetores e matrizes tendem a preferir o __array()__ para consistência.

# 2. Operações matriciais
Matrizes suportam operações aritméticas comuns.  
  
### Adicionando Matrizes
Para adicionar duas matrizes do mesmo tamanho juntas, basta adicionar os elementos correspondentes em cada matriz:  
  
\begin{equation}\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}+ \begin{bmatrix}6 & 5 & 4 \\3 & 2 & 1\end{bmatrix} = \begin{bmatrix}7 & 7 & 7 \\7 & 7 & 7\end{bmatrix}\end{equation}
  
Vamos tentar isso com Python:

In [3]:
# Importa a biblioteca NumPy.
import numpy as np

# Cria a Matriz A.
A = np.array([[1,2,3],
              [4,5,6]])

# Cria a matriz B.
B = np.array([[6,5,4],
              [3,2,1]])

# Imprime a SOMA das duas Matrizes.
print(A + B)

[[7 7 7]
 [7 7 7]]


### Subtraindo Matrizes
A subtração da matriz funciona de forma semelhante à adição de matriz:  
  
\begin{equation}\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}- \begin{bmatrix}6 & 5 & 4 \\3 & 2 & 1\end{bmatrix} = \begin{bmatrix}-5 & -3 & -1 \\1 & 3 & 5\end{bmatrix}\end{equation}

Vamos ver isso em Python:

In [4]:
# Importa a biblioteca NumPy.
import numpy as np

# Cria a Matriz A.
A = np.array([[1,2,3],
              [4,5,6]])

# Cria a matriz B.
B = np.array([[6,5,4],
              [3,2,1]])

# Imprime a SUBTRAÇÃO das duas Matrizes.
print (A - B)

[[-5 -3 -1]
 [ 1  3  5]]


###  Multiplicação de Matriz
Multiplicar matrizes é um pouco mais complexo que as operações que vimos até agora. Há dois casos a considerar:  
  
 - __Multiplicação Escalar__ (multiplicando uma matriz por um único número)  
 - __Multiplicação de matriz de produto escalar__ (multiplicando uma matriz por outra matriz  
  
### Multiplicação Escalar
Para multiplicar uma matriz por um valor escalar, basta multiplicar cada elemento pelo escalar para produzir uma nova matriz:  
  
\begin{equation}2 \times \begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix} = \begin{bmatrix}2 & 4 & 6 \\8 & 10 & 12\end{bmatrix}\end{equation}
  
Em Python, você calcula isso usando o operador __*__:

In [5]:
# Importa a biblioteca NumPy.
import numpy as np

# Cria a nossa Matriz A.
A = np.array([[1,2,3],
              [4,5,6]])

# Aplica a multiplicação Escalar.
print(2 * A)

[[ 2  4  6]
 [ 8 10 12]]


### Multiplicação de Matriz de Produtos Dot
  
Para multiplicar duas matrizes juntas, você precisa calcular o `produto escalar` de linhas e colunas.  
  
> Isso significa multiplicar cada um dos elementos em cada linha da primeira matriz por cada um dos elementos em cada coluna da segunda matriz e adicionar os resultados.  
  
Vamos ver um exemplo:  
  
\begin{equation}\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix} \cdot \begin{bmatrix}9 & 8 \\ 7 & 6 \\ 5 & 4\end{bmatrix}\end{equation}  
  
Observe que a primeira matriz é 2x3 e a segunda matriz é 3x2:  
  
> __O importante aqui é que a primeira matriz tem duas linhas e a segunda matriz tem duas colunas__.  
  
Para realizar a multiplicação, primeiro pegamos o produto escalar da primeira `linha` da primeira matriz (1,2,3) e a primeira `coluna` da segunda matriz (9,7,5):  
  
\begin{equation}(1,2,3) \cdot (9,7,5) = (1 \times 9) + (2 \times 7) + (3 \times 5) = 38\end{equation}
  
Em nossa matriz resultante __(que sempre terá o mesmo número de linhas que a primeira matriz e o mesmo número de colunas que a segunda matriz)__, podemos inserir isso na primeira linha e no primeiro elemento da coluna:  
  
\begin{equation}\begin{bmatrix}38 & ?\\? & ?\end{bmatrix} \end{equation}
  
Agora podemos pegar o produto escalar da primeira linha da primeira matriz e a segunda coluna da segunda matriz:  
  
\begin{equation}(1,2,3) \cdot (8,6,4) = (1 \times 8) + (2 \times 6) + (3 \times 4) = 32\end{equation}
  
Vamos adicionar isso à nossa matriz resultante na primeira linha e no segundo elemento da coluna:  
  
\begin{equation}\begin{bmatrix}38 & 32\\? & ?\end{bmatrix} \end{equation}  
  
Agora podemos repetir este processo para a segunda linha da primeira matriz e a primeira coluna da segunda matriz:  
  
\begin{equation}(4,5,6) \cdot (9,7,5) = (4 \times 9) + (5 \times 7) + (6 \times 5) = 101\end{equation}  
  
Que preenche o próximo elemento no resultado:  
  
\begin{equation}\begin{bmatrix}38 & 32\\101 & ?\end{bmatrix} \end{equation}  
  
Finalmente, obtemos o produto escalar para a segunda linha da primeira matriz e a segunda coluna da segunda matriz:  
  
\begin{equation}(4,5,6) \cdot (8,6,4) = (4 \times 8) + (5 \times 6) + (6 \times 4) = 86\end{equation}
  
Dando-nos:  
  
\begin{equation}\begin{bmatrix}38 & 32\\101 & 86\end{bmatrix} \end{equation}
  
Em Python, nós podemos utilizar a função __np.dot()__ do NumPy para multiplicar matrizes bidimensionais:

In [6]:
import numpy as np

# Cria uma representação da Matriz - A.
A = np.array([[1,2,3],
              [4,5,6]])

# Cria uma representação da Matriz - B.
B = np.array([[9,8],
              [7,6],
              [5,4]])

# Imprime:
# - Matriz - A;
# - Matriz - B;
# - O produto das 2 Matrizes A e B.
print(' Matriz A:\n {0}\n\n Matriz B: \n {1}\n\n A * B:\n {2}'.format(A, B, np.dot(A, B)))

 Matriz A:
 [[1 2 3]
 [4 5 6]]

 Matriz B: 
 [[9 8]
 [7 6]
 [5 4]]

 A * B:
 [[ 38  32]
 [101  86]]


__NOTE:__  
Este é um caso em que há uma diferença no comportamento entre __np.array()__ e __np.matrox()__ :  
  
 - Você também pode usar um operador de multiplicação regular ( __ *__ ) com uma __np.matrix()__
 - Mas não com uma __np.array()__  
  
Veja como fica em Python:

In [7]:
import numpy as np

# Cria a Matriz A com a função matrix().
A = np.matrix([[1,2,3]
               ,[4,5,6]])

# Cria a Matriz B com a fução matrix().
B = np.matrix([[9,8],
               [7,6],
               [5,4]])

# Veja que não utilizamos o np.dot() porque criamos
# com a função matrix().
print(A * B)

[[ 38  32]
 [101  86]]


Note que, ao contrário da multiplicação de números escalares, a ordem dos operandos em uma operação de multiplicação é significativa. Para números escalares, aplica-se a lei comutativa da multiplicação, por exemplo:  
  
\begin{equation}2 \times 4 = 4 \times 2\end{equation}
  
Com a multiplicação de matrizes, as coisas são diferentes, por exemplo:  
  
\begin{equation}\begin{bmatrix}2 & 4 \\6 & 8\end{bmatrix} \cdot \begin{bmatrix}1 & 3 \\ 5 & 7\end{bmatrix} \ne \begin{bmatrix}1 & 3 \\ 5 & 7\end{bmatrix} \cdot \begin{bmatrix}2 & 4 \\6 & 8\end{bmatrix}\end{equation}

In [8]:
import numpy as np

A = np.array([[2,4],
              [6,8]])
B = np.array([[1,3],
              [5,7]])
print(A.dot(B))

[[22 34]
 [46 74]]


# 3. Matrizes Negativas
A nagativa de uma matriz, é apenas uma matriz com o sinal de cada elemento invertido:  
  
\begin{equation}C = \begin{bmatrix}-5 & -3 & -1 \\1 & 3 & 5\end{bmatrix}\end{equation}
  
\begin{equation}-C = \begin{bmatrix}5 & 3 & 1 \\-1 & -3 & -5\end{bmatrix}\end{equation}
  
Vamos ver isso em Python.

In [9]:
# Importa a biblioteca NumPy.
import numpy as np

# Cria a Matriz C.
C = np.array([[-5,-3,-1],
              [1,3,5]])


print('Matriz C:\n {0}\n'.format(C)) # Imprime a Matriz C.
print('A Negativa da Matriz C:\n {0}'.format(-C)) # Imprime a negativa da Matriz C.

Matriz C:
 [[-5 -3 -1]
 [ 1  3  5]]

A Negativa da Matriz C:
 [[ 5  3  1]
 [-1 -3 -5]]


# 4. Transposição de Matriz 
Você pode `transpor` uma matriz, que é mudar a orientação de suas linhas e colunas. Você indica isso com um sobrescrito __T__, assim:  
  
\begin{equation}\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}^{T} = \begin{bmatrix}1 & 4\\2 & 5\\3 & 6 \end{bmatrix}\end{equation}
  
Em Python, ambos __np.array()__ e __np.matriz__ tem uma função chamada __T__ que é responsável por fazer esse tipo de operação. Vamos ver isso em Python:

In [10]:
# Importa a biblioteca NumPy.
import numpy as np

# Cria a Matriz "A".
A = np.array([[1,2,3],
              [4,5,6]])

print('Matriz A:\n {0}\n'.format(A)) # Imprime a Matriz A.
print('Transposta da Matriz A:\n {0}'.format(A.T)) # Imprime a transposta da Matriz A.

Matriz A:
 [[1 2 3]
 [4 5 6]]

Transposta da Matriz A:
 [[1 4]
 [2 5]
 [3 6]]


# 5. Matriz Identidade
Uma __Matriz Identidade__ (geralmente indicada por um maiúscula __I__) é o equivalente em termos de matriz do número __1__. Ele sempre tem o mesmo número de linhas que as colunas, e tem o valor 1 nas posições do elemento diagonal I<sub>1,1</sub>, I<sub>2,2</sub>, etc; e 0 em todas as outras posições de elemento. Aqui está um exemplo de uma matriz de identidade 3x3:  
  
\begin{equation}\begin{bmatrix}1 & 0 & 0\\0 & 1 & 0\\0 & 0 & 1\end{bmatrix} \end{equation}  
  
Multiplicar qualquer matriz por uma matriz de identidade é o mesmo que:  
  
> __Multiplicar um número por 1; o resultado é o mesmo que o valor original.__  
  
\begin{equation}\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\\7 & 8 & 9\end{bmatrix} \cdot \begin{bmatrix}1 & 0 & 0\\0 & 1 & 0\\0 & 0 & 1\end{bmatrix} = \begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\\7 & 8 & 9\end{bmatrix} \end{equation}


Se você duvida de mim, tente o seguinte código Python!

In [11]:
import numpy as np

# Cria a Matrix A.
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# Cria a Matrix B.
B = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])

# Multiplica a Matrix A,
# pelo a Matrix Identidade B.
print(A.dot(B))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


__NOTE:__  
Outa maneira de criar uma Matrix Identidade em Python é utilizar a função __np.eye()__ do NumPy.  
  
Como uma Matrix Identidade tem sempre o mesmo número de linhas e colunas (Matriz Quadrada) qualquer valor que você passar para a função ela vai determinar o mesmo número de linhas e colunas.

In [12]:
# Cria uma Matrix Identidade 3x3.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# Cria uma Matrix Identidade 5x5.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
# Cria uma Matrix Identidade 10x10.
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# 6. (Divisão Matricial) + (Recíproco de um número) + (Inverso de uma Matriz)
Antes de iniciar nossos estudos sobre `Divisão Matricial` vamos relembrar um conceito simples: __Recíproco de um número__.  
  
### Recíproco de um número
Para obter o `recíproco` de um número, dividimos 1 pelo número. Por exemplo: o recíproco de 2 é:  
  
<sup>1</sup>/<sub>2</sub>
  
### Divisão Matricial de fato
  
Você não pode realmente dividir por uma matriz; mas quando você quer dividir matrizes, você pode aproveitar o fato de que:  
  
> __A divisão por um dado número, é o mesmo que a multiplicação pelo recíproco desse número.__  
  
Por exemplo:  
  
\begin{equation}6 \div 3 = 6 \times\frac{1}{3}\end{equation}  
  
Ou:  
  
\begin{equation}6 \div 3 = \frac{1}{3}\times 6 \end{equation}  
  
Neste caso, <sup>1</sup>/<sub>3</sub> é o recíproco de 3 (que como uma fração é <sup>3</sup>/<sub>1</sub> - nós "invertemos" o numerador e o denominador para obter o recíproco). Você também pode escrever <sup>1</sup>/<sub>3</sub> como 3<sup>-1</sup>.


### Inverso de uma matriz
Para a divisão de matrizes, usamos uma ideia relacionada; nós multiplicamos pelo `inverso` de uma matriz:  
  
\begin{equation}A \div B = A \cdot B^{-1}\end{equation}  
  
O inverso de B é B<sup>-1</sup>, desde que a seguinte equação seja verdadeira:  
  
\begin{equation}B \cdot B^{-1} = B^{-1} \cdot B = I\end{equation}
  
__I__, você pode se lembrar, é uma `Matriz de Identidade - (I)`; o equivalente matricial de 1.  
  
Então, como você calcula o inverso de uma matriz? Para uma matriz 2x2, você pode seguir esta fórmula:  
  
\begin{equation}\begin{bmatrix}a & b\\c & d\end{bmatrix}^{-1} = \frac{1}{ad-bc}  \begin{bmatrix}d & -b\\-c & a\end{bmatrix}\end{equation}
  
O que aconteceu aqui?  
  
 - Nós trocamos as posições de *a* e *d*  
 - Mudamos os sinais de *b* e *c*  
 - Nós multiplicamos a matriz resultante por 1 sobre o *determinante* da matriz (*ad-bc*)  
  
Vamos tentar com alguns números reais:  
  
\begin{equation}\begin{bmatrix}6 & 2\\1 & 2\end{bmatrix}^{-1} = \frac{1}{(6\times2)-(2\times1)}  \begin{bmatrix}2 & -2\\-1 & 6\end{bmatrix}\end{equation}
  
Assim:  
  
\begin{equation}\begin{bmatrix}6 & 2\\1 & 2\end{bmatrix}^{-1} = \frac{1}{10}  \begin{bmatrix}2 & -2\\-1 & 6\end{bmatrix}\end{equation}
  
O que nos dá o resultado:  
  
\begin{equation}\begin{bmatrix}6 & 2\\1 & 2\end{bmatrix}^{-1} = \begin{bmatrix}0.2 & -0.2\\-0.1 & 0.6\end{bmatrix}\end{equation}
  
Para verificar isso, podemos multiplicar a matriz original pelo seu inverso para ver se obtemos uma matriz de identidade. Isso faz sentido se você pensar sobre isso; do mesmo modo que 3 x <sup>1</sup>/<sub>3</sub> = 1, uma matriz multiplicado pelos seus resultados inversos em uma matriz de identidade:  
  
\begin{equation}\begin{bmatrix}6 & 2\\1 & 2\end{bmatrix} \cdot \begin{bmatrix}0.2 & -0.2\\-0.1 & 0.6\end{bmatrix} = \begin{bmatrix}(6\times0.2)+(2\times-0.1) & (6\times-0.2)+(2\times0.6)\\(1\times0.2)+(2\times-0.1) & (1\times-0.2)+(2\times0.6)\end{bmatrix} = \begin{bmatrix}1 & 0\\0 & 1\end{bmatrix}\end{equation}
  
Note que nem toda matriz tem um inverso - por exemplo, se o determinante funciona como 0, a matriz inversa não é definida.  
  
No Python, você pode usar a função __np.linalg.inv()__ do NumPy para obter o inverso de uma matriz em um  objeto `matrix` ou `array`:

In [15]:
import numpy as np

# Cria a Matriz do nosso exemplo
B = np.array([[6,2],
              [1,2]])

# Pega o inverso da Matriz com a função inv() do np.linalg
print(np.linalg.inv(B))

[[ 0.2 -0.2]
 [-0.1  0.6]]


__NOTE:__  
Além disso, o __np.matrix()__ possui um método ***I*** que retorna a matriz inversa:

In [16]:
import numpy as np

# Cria a Matriz do nosso exemplo, porém,
# agora a função matrix().
B = np.matrix([[6,2],
              [1,2]])


# Utiliza o método "I" do matrix() para pegar
# a Matriz Inversa de B.
print(B.I)

[[ 0.2 -0.2]
 [-0.1  0.6]]


Para matrizes maiores, o processo para calcular o inverso é mais complexo. Vamos explorar um exemplo baseado na seguinte matriz:  
  
\begin{equation}\begin{bmatrix}4 & 2 & 2\\6 & 2 & 4\\2 & 2 & 8\end{bmatrix} \end{equation}
  
O processo para encontrar o inverso consiste nos seguintes passos:  
  
__STEP - 01:__ Crie uma matriz de *menores* calculando o *determinante* para cada elemento na matriz com base - nos elementos que __não__ estão na mesma linha ou coluna; como isso:  
  
\begin{equation}\begin{bmatrix}\color{blue}4 & \color{lightgray}2 & \color{lightgray}2\\\color{lightgray}6 & \color{red}2 & \color{red}4\\\color{lightgray}2 & \color{red}2 & \color{red}8\end{bmatrix}\;\;\;\;(2\times8) - (4\times2) = 8\;\;\;\;\begin{bmatrix}8 & \color{lightgray}? & \color{lightgray}?\\\color{lightgray}? & \color{lightgray}? & \color{lightgray}?\\\color{lightgray}? & \color{lightgray}? & \color{lightgray}?\end{bmatrix} \end{equation}

\begin{equation}\begin{bmatrix}\color{lightgray}4 & \color{blue}2 & \color{lightgray}2\\\color{red}6 & \color{lightgray}2 & \color{red}4\\\color{red}2 & \color{lightgray}2 & \color{red}8\end{bmatrix}\;\;\;\;(6\times8) - (4\times2) = 40\;\;\;\;\begin{bmatrix}8 & 40 & \color{lightgray}?\\\color{lightgray}? & \color{lightgray}? & \color{lightgray}?\\\color{lightgray}? & \color{lightgray}? & \color{lightgray}?\end{bmatrix}\end{equation}

\begin{equation}\begin{bmatrix}\color{lightgray}4 & \color{lightgray}2 & \color{blue}2\\\color{red}6 & \color{red}2 & \color{lightgray}4\\\color{red}2 & \color{red}2 & \color{lightgray}8\end{bmatrix}\;\;\;\;(6\times2) - (2\times2) = 8\;\;\;\;\begin{bmatrix}8 & 40 & 8\\\color{lightgray}? & \color{lightgray}? & \color{lightgray}?\\\color{lightgray}? & \color{lightgray}? & \color{lightgray}?\end{bmatrix} \end{equation}

\begin{equation}\begin{bmatrix}\color{lightgray}4 & \color{red}2 & \color{red}2\\\color{blue}6 & \color{lightgray}2 & \color{lightgray}4\\\color{lightgray}2 & \color{red}2 & \color{red}8\end{bmatrix}\;\;\;\;(2\times8) - (2\times2) = 12\;\;\;\;\begin{bmatrix}8 & 40 & 8\\12 & \color{lightgray}? & \color{lightgray}?\\\color{lightgray}? & \color{lightgray}? & \color{lightgray}?\end{bmatrix} \end{equation}

\begin{equation}\begin{bmatrix}\color{red}4 & \color{lightgray}2 & \color{red}2\\\color{lightgray}6 & \color{blue}2 & \color{lightgray}4\\\color{red}2 & \color{lightgray}2 & \color{red}8\end{bmatrix}\;\;\;\;(4\times8) - (2\times2) = 28\;\;\;\;\begin{bmatrix}8 & 40 & 8\\12 & 28 & \color{lightgray}?\\\color{lightgray}? & \color{lightgray}? & \color{lightgray}?\end{bmatrix} \end{equation}

\begin{equation}\begin{bmatrix}\color{red}4 & \color{red}2 & \color{lightgray}2\\\color{lightgray}6 & \color{lightgray}2 & \color{blue}4\\\color{red}2 & \color{red}2 & \color{lightgray}8\end{bmatrix}\;\;\;\;(4\times2) - (2\times2) = 4\;\;\;\;\begin{bmatrix}8 & 40 & 8\\12 & 28 & 4\\\color{lightgray}? & \color{lightgray}? & \color{lightgray}?\end{bmatrix} \end{equation}

\begin{equation}\begin{bmatrix}\color{lightgray}4 & \color{red}2 & \color{red}2\\\color{lightgray}6 & \color{red}2 & \color{red}4\\\color{blue}2 & \color{lightgray}2 & \color{lightgray}8\end{bmatrix}\;\;\;\;(2\times4) - (2\times2) = 4\;\;\;\;\begin{bmatrix}8 & 40 & 8\\12 & 28 & 4\\4 & \color{lightgray}? & \color{lightgray}?\end{bmatrix} \end{equation}

\begin{equation}\begin{bmatrix}\color{red}4 & \color{lightgray}2 & \color{red}2\\\color{red}6 & \color{lightgray}2 & \color{red}4\\\color{lightgray}2 & \color{blue}2 & \color{lightgray}8\end{bmatrix}\;\;\;\;(4\times4) - (2\times6) = 4\;\;\;\;\begin{bmatrix}8 & 40 & 8\\12 & 28 & 4\\4 & 4 & \color{lightgray}?\end{bmatrix} \end{equation}

\begin{equation}\begin{bmatrix}\color{red}4 & \color{red}2 & \color{lightgray}2\\\color{red}6 & \color{red}2 & \color{lightgray}4\\\color{lightgray}2 & \color{lightgray}2 & \color{blue}8\end{bmatrix}\;\;\;\;(4\times2) - (2\times6) = -4\;\;\;\;\begin{bmatrix}8 & 40 & 8\\12 & 28 & 4\\4 & 4 & -4\end{bmatrix} \end{equation}
  
__NOTE:__  
Veja que nós começamos a calcular pelo índice a<sub>11</sub> e como a regra diz - Na posição que estamos calculando (a<sub>11</sub>) __não__ podemos pegar elementos que estejam:  
  
 - Na mesma linha - a<sub>11</sub>  
 - Ou na mesma coluna - a<sub>11</sub>  
  
As cores `Azul` e `Vermelho` significam:  
  
 - O índice na Matriz que estamos calculando - (Azul)  
 - Os elementos que não estão na linha ou coluna do índice que estamos calculando - (Vermelho)  
  
__STEP - 02:__ Aplique *cofatores* à matriz trocando o sinal de cada elemento alternativo na matriz de menores:  
  
Se você não se lembra como aplicar os *cofatores* a aula do link abaixo pode lhe ajudar:  
[Invertendo uma matriz 3x3 calculando a matriz dos menores complementares e a matriz dos cofatores](https://www.youtube.com/watch?v=VjRCgDJPtTA)  
  
\begin{equation}\begin{bmatrix}8 & -40 & 8\\-12 & 28 & -4\\4 & -4 & -4\end{bmatrix} \end{equation}
  
O último elemento __-4__, continuou negativo mesmo depois dos cofatores, porque ele já era negativo.  
  
__STEP - 03:__ Aplica a Matriz Transposta, ou seja, as linhas vão virar colunas:  
  
\begin{equation}\begin{bmatrix}8 & \color{green}-\color{green}1\color{green}2 & \color{orange}4\\\color{green}-\color{green}4\color{green}0 & 28 & \color{purple}-\color{purple}4\\\color{orange}8 & \color{purple}-\color{purple}4 & -4\end{bmatrix} \end{equation}
  
__STEP - 04:__ Multiplique por __1/determinante da matriz original__. Para encontrar isso:
 - Multiplique cada um dos elementos da linha superior da matriz original pelos seus determinantes menores correspondentes (que calculamos anteriormente na matriz de menores);
 - Subtraia o segundo do primeiro e adicione o terceiro:  
  
Só para relembrar a matriz original é essa:  
  
\begin{equation}\begin{bmatrix}4 & 2 & 2\\6 & 2 & 4\\2 & 2 & 8\end{bmatrix} \end{equation}  
  
É a matriz dos menores é a seguinte:  
  
\begin{equation}\begin{bmatrix}8 & 40 & 8\\12 & 28 & 4\\4 & 4 & -4\end{bmatrix} \end{equation}  
  
E como o primeiro ponto do passo 4 diz - Multiplique cada um dos elementos da linha superior da matriz original pelos seus determinantes menores correspondentes, ou seja:  
  
\begin{equation}\begin{bmatrix}4 & 2 & 2\\  &   &  \\  &   &  \end{bmatrix} \end{equation}  
  
\begin{equation}\begin{bmatrix}8 & 40 & 8\\   &    &  \\  &   &   \end{bmatrix} \end{equation}  
  
Vai ficar algo parecido com isso:  
  
\begin{equation}(4 \times 8), (2 \times 40), (2 \times 8)\end{equation}
  
E como nosso segundo ponto do passo 4 diz - Subtraia o segundo do primeiro e adicione o terceiro, logo teremos a seguinte formula para encontrar o *determinante*:  
  
\begin{equation}Determinant = (4 \times 8) - (2 \times 40) + (2 \times 8) = -32\end{equation}
  
Agora, que nós já temos o determinante da matriz original (-32) vamos aplicar o que realmente importa - __1/determinante da matriz original__  
  
\begin{equation}\frac{1}{-32}\begin{bmatrix}8 & -12 & 4\\-40 & 28 & -4\\8 & -4 & -4\end{bmatrix} =  \begin{bmatrix}-0.25 & 0.375 & -0.125\\1.25 & -0.875 & 0.125\\-0.25 & 0.125 & 0.125\end{bmatrix}\end{equation}
  
Vamos verificar que a matriz original multiplicada pelos resultados inversos em uma matriz de identidade:
  
\begin{equation}\begin{bmatrix}4 & 2 & 2\\6 & 2 & 4\\2 & 2 & 8\end{bmatrix} \cdot \begin{bmatrix}-0.25 & 0.375 & -0.125\\1.25 & -0.875 & 0.125\\-0.25 & 0.125 & 0.125\end{bmatrix}\end{equation}
  
\begin{equation}= \begin{bmatrix}(4\times-0.25)+(2\times1.25)+(2\times-0.25) & (4\times0.375)+(2\times-0.875)+(2\times0.125) & (4\times-0.125)+(2\times-0.125)+(2\times0.125)\\(6\times-0.25)+(2\times1.25)+(4\times-0.25) & (6\times0.375)+(2\times-0.875)+(4\times0.125) & (6\times-0.125)+(2\times-0.125)+(4\times0.125)\\(2\times-0.25)+(2\times1.25)+(8\times-0.25) & (2\times0.375)+(2\times-0.875)+(8\times0.125) & (2\times-0.125)+(2\times-0.125)+(8\times0.125)\end{bmatrix} \end{equation}

\begin{equation}= \begin{bmatrix}1 & 0 & 0\\0 & 1 & 0\\0 & 0 & 1\end{bmatrix} \end{equation}
  
Como você pode ver, isso pode ficar bastante complicado - e é por isso que geralmente usamos uma calculadora ou um programa de computador. Você pode executar o seguinte código Python para verificar se a matriz inversa que calculamos está correta:

In [17]:
import numpy as np

# Cria uma representação da nossa Matriz original.
B = np.array([[4,2,2],
              [6,2,4],
              [2,2,8]])

# Tira a inversa da nossa matriz.
print(np.linalg.inv(B))

[[-0.25   0.375 -0.125]
 [ 1.25  -0.875  0.125]
 [-0.25   0.125  0.125]]


###  Multiplicando por uma matriz inversa 
Agora que você sabe calcular uma matriz inversa, você pode usar esse conhecimento para multiplicar o inverso de uma matriz por outra matriz como alternativa à divisão:  
  
\begin{equation}\begin{bmatrix}1 & 2\\3 & 4\end{bmatrix} \cdot \begin{bmatrix}6 & 2\\1 & 2\end{bmatrix}^{-1} \end{equation}

\begin{equation}=\begin{bmatrix}1 & 2\\3 & 4\end{bmatrix} \cdot \begin{bmatrix}0.2 & -0.2\\-0.1 & 0.6\end{bmatrix}  \end{equation}

\begin{equation}=\begin{bmatrix}(1\times0.2)+(2\times-0.1) & (1\times-0.2)+(2\times0.6)\\(3\times0.2)+(4\times-0.1) & (3\times-0.2)+(4\times0.6)\end{bmatrix}\end{equation}

\begin{equation}=\begin{bmatrix}0 & 1\\0.2 & 1.8\end{bmatrix}\end{equation}

Aqui está o código Python para calcular isso:

In [18]:
import numpy as np

# Cria uma representação da Matriz A.
A = np.array([[1,2],
              [3,4]])

# Cria uma representação da Matriz B
B = np.array([[6,2],
              [1,2]])

# Multiplica a Matriz A pelo o inverso da Matriz B.
C = A.dot(np.linalg.inv(B))

print(C) # Imprime o resultado.

[[0.  1. ]
 [0.2 1.8]]


# 7. Resolvendo Sistemas de Equações com Matrizes
  
Uma das grandes coisas sobre matrizes é que elas podem nos ajudar a resolver sistemas de equações. Por exemplo, considere o seguinte sistema de equações:  
  
\begin{equation}2x + 4y = 18\end{equation}
\begin{equation}6x + 2y = 34\end{equation}
  
Podemos escrever isso em forma de matriz, assim:  
  
\begin{equation}\begin{bmatrix}2 & 4\\6 & 2\end{bmatrix} \cdot \begin{bmatrix}x\\y\end{bmatrix}=\begin{bmatrix}18\\34\end{bmatrix}\end{equation}
  
Observe que as variáveis (__x__ e __y__) são organizadas como uma coluna em uma matriz, que é multiplicada por uma matriz contendo os coeficientes para produzir uma matriz contendo os resultados.  
  
Se você calcular o produto escalar no lado esquerdo, poderá ver claramente que isso representa as equações originais:  
  
\begin{equation}\begin{bmatrix}2x + 4y\\6x + 2y\end{bmatrix} =\begin{bmatrix}18\\34\end{bmatrix}\end{equation}
  
Agora. vamos nomear nossas matrizes para que possamos entender melhor o que vem a seguir:  
  
\begin{equation}A=\begin{bmatrix}2 & 4\\6 & 2\end{bmatrix}\;\;\;\;X=\begin{bmatrix}x\\y\end{bmatrix}\;\;\;\;B=\begin{bmatrix}18\\34\end{bmatrix}\end{equation}
  
Nós já sabemos que ***A &bull; X = B***, o que significa aritmeticamente que ***X = B &div; A*** (o __A__ estava de um lado multiplicando, o que fizemos foi passar para o outro lado dividindo - como em equações). Como não podemos realmente dividir por uma matriz, precisamos multiplicar pelo inverso; então podemos encontrar os valores para nossas variáveis (`X`) assim: ***X = A<sup>-1</sup> &bull; B***  
  
Então, primeiro precisamos do inverso de A:  
  
\begin{equation}\begin{bmatrix}2 & 4\\6 & 2\end{bmatrix}^{-1} = \frac{1}{(2\times2)-(4\times6)}  \begin{bmatrix}2 & -4\\-6 & 2\end{bmatrix}\end{equation}
  
\begin{equation}= \frac{1}{-20}  \begin{bmatrix}2 & -4\\-6 & 2\end{bmatrix}\end{equation}
  
\begin{equation}=\begin{bmatrix}-0.1 & 0.2\\0.3 & -0.1\end{bmatrix}\end{equation}
  
Então nós apenas multiplicamos isso com __B__:  
  
\begin{equation}X = \begin{bmatrix}-0.1 & 0.2\\0.3 & -0.1\end{bmatrix} \cdot \begin{bmatrix}18\\34\end{bmatrix}\end{equation}
  
\begin{equation}X = \begin{bmatrix}(-0.1 \times 18)+(0.2 \times 34)\\(0.3\times18)+(-0.1\times34)\end{bmatrix}\end{equation}
  
\begin{equation}X = \begin{bmatrix}5\\2\end{bmatrix}\end{equation}
  
A matriz resultante (__X__) contém os valores para nossas variáveis __x__ e __y__, e podemos verificar estes ligando-os nas equações originais:  
  
\begin{equation}(2\times5) + (4\times2) = 18\end{equation}
\begin{equation}(6\times5) + (2\times2) = 34\end{equation}
  
Estes, obviamente, simplificam para:  
  
\begin{equation}10 + 8 = 18\end{equation}
\begin{equation}30 + 4 = 34\end{equation}
  
Portanto, nossos valores variáveis estão corretos.  
  
Aqui está o código Python para fazer tudo isso:

In [19]:
import numpy as np

# A matriz A vai representa os coeficientes da equação:
# - 2x + 4y = 18
# - 6x + 2y = 34
A = np.array([[2,4],
              [6,2]])

# A matriz B vai representa os resultados finais das equações.
B = np.array([[18],
              [34]])

# Agora vamos criar de fato nossa formula para resolver o Sistema Linear:
# A • X = B =
# X = B ÷ A =
# X = A^1 • B
# Ou seja, vamos aplicar a multiplicação da matriz inversa de A
# com a matriz B: X = A^1 • B
C = np.dot(np.linalg.inv(A), B)

print(C) # Imprime o resultado.

[[5.]
 [2.]]


__NOTE:__  
Na nossa saída em Python o  __x = 5__ e __y = 2__:  
  
2x + 4y = 18  
6x + 2y = 34  
  
Que é equivalente:  
  
2x5 + 4x2 = 18  
6x5 + 2x2 = 34  

__ESTUDOS ADICIONAIS:__  
[Recíproco de um número - (Reciprocal of a number)](https://www.mathsisfun.com/reciprocal.html)  
[Invertendo uma matriz 3x3 calculando a matriz dos menores complementares e a matriz dos cofatores](https://www.youtube.com/watch?v=VjRCgDJPtTA)  