# Matrizes
Em termos gerais, uma matriz é uma array de números organizados em __linhas__ e __colunas__.

# 1. Matrizes e notação de matriz
Uma matriz organiza números em __linhas__ e __colunas__, assim:  
  
\begin{equation}A = \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6
 \end{bmatrix}
\end{equation}
  
Observe que as matrizes geralmente são nomeadas como uma letra maiúscula. Referimo-nos aos `elementos` da matriz usando o equivalente em minúscula com um indicador de linha e coluna subscrito, assim:  
  
\begin{equation}A = \begin{bmatrix}
  a_{1,1} & a_{1,2} & a_{1,3} \\
  a_{2,1} & a_{2,2} & a_{2,3}
 \end{bmatrix}
\end{equation}
  
Em Python, você pode definir uma Matriz 2-dimensional com a função __np.array()__ do NumPy:

In [1]:
# Importa a biblioteca NumPy.
import numpy as np

# Cria nossa Matriz com o método array() do NumPy.
A = np.array([[1,2,3],
              [4,5,6]])

print(A) # Imprime a Matriz.

[[1 2 3]
 [4 5 6]]


Você também pode usar o __np.matrix()__ que é uma subclasse especializada de matrizes(arrays):

In [2]:
import numpy as np

# cria uma Matriz, porém de forma especializada.
M = np.matrix([[1,2,3],
               [4,5,6]])

print(M) # Imprime a Matriz.

[[1 2 3]
 [4 5 6]]


Existem algumas diferenças de comportamento entre __array()__ e __matrix()__ - Especialmente com relação à multiplicação (que vamos explorar mais tarde). Você pode usar qualquer um, mas os programadores Python mais experientes que precisam trabalhar com vetores e matrizes tendem a preferir o __array()__ para consistência.

# 2. Operações matriciais
Matrizes suportam operações aritméticas comuns.  
  
### Adicionando Matrizes
Para adicionar duas matrizes do mesmo tamanho juntas, basta adicionar os elementos correspondentes em cada matriz:  
  
\begin{equation}\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}+ \begin{bmatrix}6 & 5 & 4 \\3 & 2 & 1\end{bmatrix} = \begin{bmatrix}7 & 7 & 7 \\7 & 7 & 7\end{bmatrix}\end{equation}
  
Vamos tentar isso com Python:

In [3]:
# Importa a biblioteca NumPy.
import numpy as np

# Cria a Matriz A.
A = np.array([[1,2,3],
              [4,5,6]])

# Cria a matriz B.
B = np.array([[6,5,4],
              [3,2,1]])

# Imprime a SOMA das duas Matrizes.
print(A + B)

[[7 7 7]
 [7 7 7]]


### Subtraindo Matrizes
A subtração da matriz funciona de forma semelhante à adição de matriz:  
  
\begin{equation}\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}- \begin{bmatrix}6 & 5 & 4 \\3 & 2 & 1\end{bmatrix} = \begin{bmatrix}-5 & -3 & -1 \\1 & 3 & 5\end{bmatrix}\end{equation}

Vamos ver isso em Python:

In [4]:
# Importa a biblioteca NumPy.
import numpy as np

# Cria a Matriz A.
A = np.array([[1,2,3],
              [4,5,6]])

# Cria a matriz B.
B = np.array([[6,5,4],
              [3,2,1]])

# Imprime a SUBTRAÇÃO das duas Matrizes.
print (A - B)

[[-5 -3 -1]
 [ 1  3  5]]


#### Conformability
In the previous examples, we were able to add and subtract the matrices, because the *operands* (the matrices we are operating on) are ***conformable*** for the specific operation (in this case, addition or subtraction). To be conformable for addition and subtraction, the operands must have the same number of rows and columns. There are different conformability requirements for other operations, such as multiplication; which we'll explore later.

### Matrizes Negativas
A nagativa de uma matriz, é apenas uma matriz com o sinal de cada elemento invertido:  
  
\begin{equation}C = \begin{bmatrix}-5 & -3 & -1 \\1 & 3 & 5\end{bmatrix}\end{equation}
  
\begin{equation}-C = \begin{bmatrix}5 & 3 & 1 \\-1 & -3 & -5\end{bmatrix}\end{equation}
  
Vamos ver isso em Python.

In [5]:
# Importa a biblioteca NumPy.
import numpy as np

# Cria a Matriz C.
C = np.array([[-5,-3,-1],
              [1,3,5]])


print('Matriz C:\n {0}\n'.format(C)) # Imprime a Matriz C.
print('A Negativa da Matriz C:\n {0}'.format(-C)) # Imprime a negativa da Matriz C.

Matriz C:
 [[-5 -3 -1]
 [ 1  3  5]]

A Negativa da Matriz C:
 [[ 5  3  1]
 [-1 -3 -5]]


### Transposição de Matriz 
Você pode `transpor` uma matriz, que é mudar a orientação de suas linhas e colunas. Você indica isso com um sobrescrito __T__, assim:  
  
\begin{equation}\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}^{T} = \begin{bmatrix}1 & 4\\2 & 5\\3 & 6 \end{bmatrix}\end{equation}
  
Em Python, ambos __np.array()__ e __np.matriz__ tem uma função chamada __T__ que é responsável por fazer esse tipo de operação. Vamos ver isso em Python:

In [6]:
# Importa a biblioteca NumPy.
import numpy as np

# Cria a Matriz "A".
A = np.array([[1,2,3],
              [4,5,6]])

print('Matriz A:\n {0}\n'.format(A)) # Imprime a Matriz A.
print('Transposta da Matriz A:\n {0}'.format(A.T)) # Imprime a transposta da Matriz A.

Matriz A:
 [[1 2 3]
 [4 5 6]]

Transposta da Matriz A:
 [[1 4]
 [2 5]
 [3 6]]
